spring.application.name=tax-gap-compliance-service

server.port=8090

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.flyway.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.datasource.url=jdbc:postgresql://localhost:5432/tax_compliance
spring.datasource.username=postgres
spring.datasource.password=billing
